name: Terraform Infrastructure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials using GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Specify the version of Terraform you need

      # Step 4: Run Terraform init, plan, and apply to create the infrastructure (ECR repo and IAM roles)
      - name: Terraform Apply
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        env:
          TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}

      # Step 5: Create ECR repository using Terraform (If not already created)
      - name: Create ECR repository (if not exists)
        run: |
          # Define your ECR repository resource in Terraform if it doesn't already exist
          terraform import aws_ecr_repository.my_repository <ecr-repository-arn> || terraform apply -auto-approve
        env:
          TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}

      # Step 6: Configure kubectl and install Helm (if not pre-installed)
      - name: Install kubectl & Helm, Configure EKS
        run: |
          # Check if kubectl is already installed (optional step)
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl"
            curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          fi

          # Check if Helm is already installed (optional step)
          if ! command -v helm &> /dev/null; then
            echo "Installing Helm"
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          fi

          # Configure kubectl to use the EKS cluster
          aws eks update-kubeconfig --name ${{ secrets.TF_VAR_CLUSTER_NAME }} --region ${{ secrets.AWS_DEFAULT_REGION }}

      # Step 7: Install Nginx Ingress Controller using Helm
      - name: Install Nginx Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install nginx-ingress ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --set controller.service.type=LoadBalancer

      # Step 8: Verify the installation of Nginx Ingress Controller
      - name: Verify Nginx Ingress Controller
        run: |
          kubectl get pods -n ingress-nginx
          kubectl get svc -n ingress-nginx
